### ISSUE TITLE
输入wx+空格 ，再输入信息就会直接报错，让我重新启动微信

### ISSUE THREAD

**Issue by xuxchao** [TKkk-iOSer/wechat-alfred-workflow#25]
输入wx+空格 ，再输入信息就会直接报错，让我重新启动微信。确认版本已经升级到2.0了

**Comment by YarnYang** [comment]
我也是这个问题！wx+空格 微信就自动退出了

**Comment by dreistein543** [comment]
附议楼上，补充说明：如果仅输入`wx`可以调用workflow所有功能，包括查询聊天记录和与对象聊天（输入`wx`时可以查看最近聊天对象）
所安装各软件版本如下：
1. workflow：2.0, 安装来源：本站code页
1.1 微信助手: 1.7.1,安装方法：`terminal`输入
```
curl -o- -L https://raw.githubusercontent.com/lmk123/oh-my-wechat/master/install.sh | bash -s
```
2. Alfred: v3.6.2
3. WeChat: 2.3.18

**Comment by Yanqilong** [comment]
同文，输入 wx+空格+内容造成微信闪退

**Comment by zqso** [comment]
只能暂时把微信退回 2.3.17了。

**Comment by woheme** [comment]
看来都出现了这个问题

**Comment by dreistein543** [comment]
亲测微信回退到2.3.17后问题解决

**Comment by hexid26** [comment]
看来又要烦请TK 大神更新脚本了

**Comment by wangjianghu** [comment]
alfred 输入wx+任意字符 回车后微信闪退
Alfred: 3.7
WeChat: 2.3.19

**Comment by leochan2017** [comment]
我也是，系统版本：OS 10.14

**Comment by nikochenbycn** [comment]
回退微信版本 2.3.17 解决，感谢~

**Comment by wishcn** [comment]
Process:               WeChat [617]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.3.18 (11431)
App Item ID:           836500024
App External ID:       828371835
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [617]
User ID:               501

Date/Time:             2018-10-10 10:19:56.900 +0800
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        XXXX


Time Awake Since Boot: 710 seconds

System Integrity Protection: enabled

Crashed Thread:        15  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

**Comment by sfdye** [comment]
alfred: 3.7
wechat: 2.3.18
macOS: 10.14 

一样的问题

想问下大家都是到哪下的以往版本？

**Comment by leochan2017** [comment]
> alfred: 3.7
> wechat: 2.3.18
> macOS: 10.14
> 
> 一样的问题
> 
> 想问下大家都是到哪下的以往版本？



没有下载旧版本。暂停使用此功能，等插件作者更新

**Comment by TKkk-iOSer** [comment]
已经更新了，重新安装下 https://github.com/TKkk-iOSer/WeChatPlugin-MacOS  切记用普通安装

**Comment by sfdye** [comment]
@TKkk-iOSer 亲测手动安装2.3.18可以用了，但是omw还不行，大大可以出个新tag `1.7.3`吗?

**Comment by sfdye** [comment]
@TKkk-iOSer 

但好像又出了这个问题，已经好几次了

![image](https://user-images.githubusercontent.com/1016390/47071880-494ada80-d227-11e8-88cc-c39cf553f9a3.png)

**Comment by leochan2017** [comment]
> @TKkk-iOSer
> 
> 但好像又出了这个问题，已经好几次了
> 
> ![image](https://user-images.githubusercontent.com/1016390/47071880-494ada80-d227-11e8-88cc-c39cf553f9a3.png)

是的是的，我刚刚更新完，测试了一下。wx + 能搜到的人就不报错重启。  如果wx + 不存在的人关键词就报错重启

**Comment by TKkk-iOSer** [comment]
![img](https://user-images.githubusercontent.com/11961989/47075762-c7ab7a80-d22f-11e8-90d1-57b995227c05.gif)
@sfdye @leochan2017  我的不会…刚下的最新 2.3.18 的，有什么必现的路径么

**Comment by sfdye** [comment]
@TKkk-iOSer 我只有截图的问题 很随机 大概每5分钟退出一次 而且卸载插件还不行 只能重装微信

**Comment by TKkk-iOSer** [comment]
@sfdye 提示重新登录但是不会崩溃是么？如果会崩溃的话提供下日志

**Comment by sfdye** [comment]
@TKkk-iOSer 只是强制登出 没有崩溃

**Comment by wangjianghu** [comment]
输入 wx 加空格微信就闪退了

**Comment by TKkk-iOSer** [comment]
Fixed
